name: Deploy to Thirdvizion Server

on:
  push:
    branches:
      - main  # Trigger deployment on push to main branch

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Set up SSH
        run: |
          echo "${{ secrets.DEV_KEY }}" | base64 --decode > ec2_key.pem
          chmod 400 ec2_key.pem

      - name: SSH and Pull Latest Code
        env:
          EC2_HOST: ${{ secrets.DEV_HOST }}
          EC2_USER: ${{ secrets.DEV_USER }}
        run: |
          ssh -i ec2_key.pem -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST << 'EOF'
            cd /home/ubuntu/demo/deploy-node-vps-github-action
            sudo git reset --hard
            sudo git checkout main
            sudo git pull origin main
            sudo npm install
            sudo pm2 restart github-action-demo
          EOF

      - name: Clean up
        run: rm ec2_key.pem
